---
#inspired: https://discussion.fedoraproject.org/t/playing-around-with-fedora-coreos-using-vagrant-libvirt-on-fedora-silverblue/1704/1

- name: directory for Dockerfile
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true

# https://developer.hashicorp.com/packer/install
- name: Dockerfile
  ansible.builtin.blockinfile:
    path: "{{ docker_dir }}/Dockerfile"
    create: true
    block: |
      FROM docker://registry.fedoraproject.org/fedora:latest
      RUN dnf install -y dnf-plugins-core
      RUN dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
      RUN dnf -y install packer
      CMD [ "/bin/bash" ]
  #FROM docker://registry.fedoraproject.org/fedora:{{ podman_fedora_version }}

- name: Build image
  containers.podman.podman_image:
    name: localhost/packer-container:latest
    path: "{{ docker_dir }}"
    state: build
    force: "{{ rebuild_podman }}"
    build:
      rm: true

- debug:
    msg: "Rebuild podman: {{ rebuild_podman }}"
  when: rebuild_podman

- name: Add to shell alias
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    append_newline: true
    prepend_newline: true
    marker_begin: "podman Packer BEGIN"
    marker_end: "podman Packer END"
    create: true
    block: |
      alias packer='podman run --rm -it \
        --volume /run/libvirt:/run/libvirt \
        --volume "${HOME}:${HOME}:rslave" \
        --env "HOME=${HOME}" \
        --workdir "$(pwd)" \
        --net host \
        --privileged \
        --security-opt label=disable \
        --entrypoint /usr/bin/packer \
        localhost/packer-container:latest'
